CREATE TABLE USER
(
    ID   INTEGER NOT NULL,
    NAME VARCHAR NOT NULL,
    PASSWD VARCHAR NOT NULL
);
INSERT INTO USER VALUES (1,'user1','passwd1');
INSERT INTO USER VALUES (2,'user2','passwd2');
INSERT INTO USER VALUES (3,'user3','passwd3');
